# uc = UserDa()
# print(verify_user_for_post(uc.find_by_id_internal(User, 1)))
# # print(user_id_validator(20))
# db = DatabaseManager()
# print(db.find_by_id_internal(Post,21))
# print(verify_post_for_comment(db.find_by_id_internal(Post, 211)))
# # user = db.find_by_id_internal(User, 90)
# # #post=db.find_by_id_internal(Post, 10)
# # print(post_id_validator(9))
