from controller.comment_controller import CommentController
from controller.like_controller import LikeController
from controller.post_controller import PostController
from controller.user_controller import UserController